import type React from "react"
import "./globals.css"
import { Roboto } from "next/font/google"
import { LanguageProvider } from "@/lib/language-context"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // you can add more if needed
  variable: "--font-roboto",
})

export const metadata = {
  title: "Your App",
  description: "Generated by Next.js",
    generator: 'v0.app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  )
}
